name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use valgrind
      run: |
        cargo install cargo-valgrind
        sudo apt install valgrind
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo test --verbose
        cargo test --verbose --release
        cargo valgrind test --verbose
        cargo valgrind test --verbose --release
